name: alunideas
favicon: null
layout_spectrum: 1
typography_spectrum: 0.15228
title: Blog de alunideas.com
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-54375144-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#f15b29'
    - '#800301'
    - '#cd2300'
    - '#efccc7'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
