name: alunideas
favicon: null
layout_spectrum: 1
typography_spectrum: 0.15228
title: Blog oficial del mundo de las ideas
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-54375144-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#51cceb'
    - '#834c45'
    - '#ffffff'
    - '#fc7e29'
    - '#009ad6'
  brandStrength: 1
  lightness: 0
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
