name: alunideas
favicon: null
layout_spectrum: 0
typography_spectrum: 0.16295
title: Blog
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-54375144-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#f15b29'
    - '#800301'
    - '#cd2300'
    - '#efccc7'
  brandStrength: 0.75
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
