name: alunideas
favicon: null
layout_spectrum: 1
typography_spectrum: 0.15228
title: Blog oficial del mundo de las ideas
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-54375144-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 1
  lightness: 0
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
