name: alunideas
favicon: null
layout_spectrum: 0.7193504206370562
typography_spectrum: 0.7832270725630224
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.9500940223224461
  lightness: 0.1855535909999162
  saturation: 0.7629658705554903
  rhythmicContrast: 0.5231843416113406
purpose: []
